void dir();
int  opc();
void limpar_tela();
void upper(char *str);
void remover_quebra(char *str);
void limpar_teclado();
void tipo_de_erro(int n);
void ler_datas();
void formatar_cpf(char *cpf_formatado);
int confirmar();
void test_fun(char c);
void pausa();
void load();
