#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <ctype.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>

#include "elements.h"
#include "globals.h"
#include "datas.h"
#include "services.h"
#include "fatura.h"
#include "log.h"
#include "hotel.h"
#include "rooms.h"
#include "files.h"
#include "base.h"
#include "guest.h"
#include "search.h"
#include "texts.h"
#include "sis.h"
#include "cfg.h"